modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "stackabletrims"
version = "${version}"
displayName = "Stackable Trims"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.stackabletrims]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stackabletrims]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stackabletrims]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"