modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "GPL 3.0"

[[mods]]
modId = "stackabletrims"
version = "${version}"
displayName = "Stackable Trims"
authors = "Golem"
description = '''
Allows you to stack as many trims as you want!
'''
#logoFile = ""

[[dependencies.stackabletrims]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stackabletrims]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stackabletrims]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.0,)"
ordering = "AFTER"
side = "BOTH"